add_newline = false

format = '''
$directory$git_branch$git_status$character
'''

right_format = '''
$battery
'''

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[character]
success_symbol = '\$'
error_symbol = '[\$](red)'

[battery]
format = "$symbol$percentage"

[[battery.display]]
threshold = 100
