#!/bin/bash

checkupdates
if [[ $? == 0 ]]; then
  notify-send -u critical 'Updates Available' 'Run pacman -Syu to install available updates'
fi

aur check
if [[ $? == 0 ]]; then
  notify-send -u critical 'AUR Updates Available' 'Run aur check to view available updates'
fi
