#!/bin/bash

checkupdates
if [[ $? == 0 ]]; then
  notify-send 'Updates Available' 'Run pacman -Syu to install available updates'
else
  notify-send 'No Updates Available' 'All installed packages are up-to-date'
fi
