#!/usr/bin/bash

name=${1%.*}

if [[ -z "$3" ]]; then
    alpha="95"
else
    alpha="$3"
fi

if [[ -f "$name.json" ]]; then
    wal --cols16 darken -f "$name.json" -a $alpha
else
    if [[ $2 == "l" ]]; then
        wal --cols16 lighten -i "$1" -a $alpha
    else
        wal --cols16 darken -i "$1" -a $alpha
    fi
fi
makoctl reload
eww reload
swww img -t wipe $1

eww active-windows | grep "bar"
if [[ ! $? ]]; then
    eww close bar
    eww open bar
fi

