#!/usr/bin/bash

set -e

if [ $# == 0 ]; then
    echo "Usage: wallpaper [path_to_image] <l|d> <alpha> <rofi-gravity>"
    exit 1
fi

name=${1%.*}

if [[ -z "$3" ]]; then
    alpha="95"
else
    alpha="$3"
fi

if [[ -f "$name.json" ]]; then
    wal --cols16 darken -f "$name.json" -a $alpha
else
    if [[ $2 == "l" ]]; then
        kind="lighten"
    else
        kind="darken"
    fi
    wal --cols16 $kind -i "$1" -a $alpha --contrast 2.0 # extra contrast so I can actually see things
fi

makoctl reload
eww reload
swww img -t wipe $1
killall -SIGUSR2 waybar
